### ISSUE TITLE
Add catalogues

### ISSUE THREAD

**Issue by rainsworth** [rainsworth/lbbw_quality#4]
Add TGSS, NVSS, etc. to a catalogues sub-directory.

**Comment by rainsworth** [comment]
Add FIRST

**Comment by alexmatze** [comment]
TGSS should work
FIRST is implemented and must be tested.
NVSS not yet implemented
LOTS also to be added (path-variables already are prepared)

**Comment by rainsworth** [comment]
LOTS_Server should be changed to LoTSS (or LOTSS) and modified wherever it is used

**Comment by alexmatze** [comment]
fixed
